// This file is auto-generated by the object generator script.
// It exports the SHA-1 hash of the root tree object for easy access.
export const ROOT_HASH = 'b155325039408df00f1cea8f47af1dedda6f5ae4';
