// This file is auto-generated by the object generator script.
// It exports the SHA-1 hash of the root tree object for easy access.
export const ROOT_HASH = '55a30b187b9f0a9f8b8b130fc20aa777e0335caa';
