// This file is auto-generated by the object generator script.
// It exports the SHA-1 hash of the root tree object for easy access.
export const ROOT_HASH = '0ae84e9bf97dba8cd50385e57eab8e51b4f289a6';
